# Version of Docker compose file
version: "3.6"

# Apps
services:

  # Download client
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=lobohastamorir #optional
      - PASS=huevos1 #optional

    volumes:
      - ${USERDIR}/transmission:/config
      - ${DOWNLOADDIR}:/media/downloads
      - ${DOWNLOADDIR}/watch:/media/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8086
      - TORRENTING_PORT=6881
    volumes:
      - ${USERDIR}/qbittorrent/appdata:/config
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jdownloader-2:
    container_name: jdownloader-2
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ${USERDIR}/jdownloader-2:/config:rw
      - ${DOWNLOADDIR}/jdownloader:/output:rw
    restart: unless-stopped

  # Torrent provider
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
