# Version of Docker compose file
version: "3.6"

# Apps
services:

  # Download client
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=lobohastamorir #optional
      - PASS=huevos1 #optional
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ${USERDIR}/transmission:/config
      - ${USERDIR}/transmission/combustion-ui:/combustion-release
      - ${DOWNLOADDIR}:/downloads
      - ${DOWNLOADDIR}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    
  jdownloader-2:
    container_name: jdownloader
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ${USERDIR}/jdownloader-2:/config:rw
      - ${DOWNLOADDIR}/jdownloader:/output:rw

  # Torrent provider
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
    volumes:
      - ${USERDIR}/jackett:/config
      - ${DOWNLOADDIR}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
