# Version of Docker compose file
version: "3"

# Apps
services:
  # Basics
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup