# Version of Docker compose file
version: "3"

# Apps
services:

  # Media request
  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/overseerr:/app/config
    ports:
      - 5055:5055

  # Media management
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr:/config
      - ${MEDIADIR}/Series:/tv
      - ${DOWNLOADDIR}:/downloads
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr:/config
      - ${MEDIADIR}/Movies:/movies #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 7878:7878
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/lidarr:/config
      - ${MEDIADIR}/Music:/music
      - ${DOWNLOADDIR}:/downloads
    ports:
      - 8686:8686
  readarr:
    image: linuxserver/readarr
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/readarr:/config
      - ${MEDIADIR}/Books:/books #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8787:8787
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/bazarr:/config
      - ${MEDIADIR}/Movies:/movies #optional
      - ${MEDIADIR}/Series:/tv #optional
    ports:
      - 6767:6767

# Media Viewing
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=claim-fEN1RgqeP8g8kCMQzvzV
    volumes:
      - ${USERDIR}/plex:/config
      - ${MEDIADIR}:/media
    restart: unless-stopped
