# Version of Docker compose file
version: "3.6"

# Apps
services:
  # Media management
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr:/config
      - ${MEDIADIR}/Series:/tv #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr:/config
      - ${MEDIADIR}/Movies:/movies #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/lidarr:/config
      - ${MEDIADIR}/Music:/music #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/readarr:/config
      - ${MEDIADIR}/Books:/books #optional
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/bazarr:/config
      - ${MEDIADIR}/Movies:/movies #optional
      - ${MEDIADIR}/Series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${USERDIR}/calibre-web:/config
      - ${MEDIADIR}/Books:/books
      - ${DOWNLOADDIR}:/downloads #optional
    ports:
      - 8097:8083
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${USERDIR}/overseerr:/app/config
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex-media
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-fEN1RgqeP8g8kCMQzvzV
    volumes:
      - ${USERDIR}/plex:/config
      - ${MEDIADIR}:/media
    restart: unless-stopped
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host