# Version of Docker compose file
version: "3.6"

# Apps
services:
  # Basics
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
  adguardhome:
      image: adguard/adguardhome
      container_name: adguardhome
      network_mode: bridge
      ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
      volumes:
        - ${USERDIR}/adguardhome/work:/opt/adguardhome/work
        - ${USERDIR}/adguardhome/conf:/opt/adguardhome/conf
      restart: unless-stopped
