# Version of Docker compose file
version: "3"

# Apps
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  hoobs:
    container_name: hoobs
    image: hoobs/hoobs
    volumes:
      - /home/pi/hoobs:/hoobs
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  homeassistant:
    container_name: home-assistant
    image: linuxserver/homeassistant:latest
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
